version: '3.7'
services:
  pg-database:
    image: postgres:latest
    restart: on-failure
    container_name: pg-database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    networks:
      - snetwork
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - snetwork

  migrate:
    image: migrate/migrate
    depends_on:
      - pg-database
    volumes:
        - ./api_sisms/db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@pg-database:5432/sismic?sslmode=disable", "up", "3"]
    links:
        - pg-database
    networks:
      - snetwork

  api_sisms:
    image: kiramishima/sismic:v1
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./api_sisms/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - pg-database
    networks:
      - snetwork

  front_sisms:
    image: kiramishima/sismicfront:v1
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./sismic-front/Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - api_sisms
    restart: on-failure:5

networks:
      snetwork: